name: Build and Publish image to Docker Hub

on:
  push:
    branches:
      - main
      - visualisation_features

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build --no-cache  . -t qvillo/audit_anomaly_detection_app:latest

      - name: Push Docker image to Docker Hub
        run: docker push qvillo/audit_anomaly_detection_app:latest

